name = "ebook-donatjs-api"
main = "src/index.js"
compatibility_date = "2026-01-01"

# Ganti dengan account_id milikmu (opsional jika sudah login via wrangler)
# account_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[d1_databases]]
binding = "DB"
database_name = "db-bukugue"
database_id = "22f2a65c-8d56-4e50-ac8d-90c7e6a63e4a"

# Set via: wrangler secret put JWT_SECRET
# Set via: wrangler secret put GOOGLE_CLIENT_ID
[vars]
# Non-secret vars boleh taruh di sini, contoh:
ALLOWED_ORIGIN = "https://kuplug.github.io"

[observability]
enabled = true
